language: python
python: 3.6

branches:
  only:
  - master

install:
  - curl -L https://raw.githubusercontent.com/nicklinyi/install/master/install-hugo.sh | bash
  - pip install pygments
  - git submodule update --remote


script:
  - ./hugo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GH_TOKEN}
  local_dir: public
