language: python
python: 3.7

before_install:
  - cd ..
  - git clone --depth=50 --branch=master https://github.com/nicklinyi/blog.git myblog
  - cd myblog
  - git submodule update --init --remote

install:
  - curl -L https://raw.githubusercontent.com/nicklinyi/install/master/install-hugo.sh | bash
  - pip install pygments

script:
  - ./hugo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GH_TOKEN}
  local_dir: ../myblog/public
